version: '3.1'

services:
  couchdb:
    build:
      dockerfile: couchdb.Dockerfile
      context: .
    image: single-node-couchdb
    volumes:
      - couchdb-data:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      - product-catalog
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    env_file:
      - .env

volumes:
  couchdb-data:
    driver: local

networks:
  product-catalog:
    driver: bridge
